name: Optimize map and deploy vereinspraesi
on:
  schedule:
    - cron: "1 6 * * *" # 7:01 German time
    - cron: "1 17 * * *" #18:01 German time
  push:
    branches:
      - vpmaster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          ls -al          
          git checkout vpmaster
          git config --global user.email "$(git log HEAD --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          deploy/setAudioStream.sh
          rm -rfv ./deploy/
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: vereinspraesi # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: vpmaster

      - name: Bash2
        run: |
          ls -al
